from __future__ import annotations

import argparse
import ast
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
METRICS_PATH = ROOT / "docs" / "metrics.json"
README_PATH = ROOT / "README.md"
START = "<!-- metrics:start -->"
END = "<!-- metrics:end -->"

sys.path.insert(0, str(SRC))


def count_tests() -> int:
    count = 0
    for path in sorted((ROOT / "tests").glob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        count += sum(
            1
            for node in ast.walk(tree)
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test_")
        )
    return count


def count_cli_commands() -> int:
    import argparse as argparse_module

    from codex_armada.cli import build_parser

    parser = build_parser()
    for action in parser._actions:  # argparse intentionally has no public subparser iterator.
        if isinstance(action, argparse_module._SubParsersAction):
            return len(action.choices)
    raise RuntimeError("Could not find CLI subcommands")


def python_metrics() -> tuple[int, int, int]:
    files = sorted(path for path in (SRC / "codex_armada").rglob("*.py") if "__pycache__" not in path.parts)
    physical = 0
    nonblank = 0
    for path in files:
        lines = path.read_text(encoding="utf-8").splitlines()
        physical += len(lines)
        nonblank += sum(1 for line in lines if line.strip())
    return len(files), physical, nonblank


def calculate() -> dict[str, object]:
    with (SRC / "codex_armada" / "resources" / "default_config.toml").open("rb") as stream:
        config = tomllib.load(stream)
    with (ROOT / "pyproject.toml").open("rb") as stream:
        project = tomllib.load(stream)

    modules, physical_lines, nonblank_lines = python_metrics()
    rates = config["credit_rates"]
    sol_input = float(rates["gpt-5.6-sol"]["input_per_million"])
    luna_input = float(rates["gpt-5.6-luna"]["input_per_million"])
    terra_input = float(rates["gpt-5.6-terra"]["input_per_million"])
    return {
        "project": project["project"]["name"],
        "version": project["project"]["version"],
        "python_source_modules": modules,
        "python_source_lines_physical": physical_lines,
        "python_source_lines_nonblank": nonblank_lines,
        "automated_test_cases": count_tests(),
        "cli_commands": count_cli_commands(),
        "routing_profiles": len(config["profiles"]),
        "model_aliases": len(config["models"]),
        "risk_rules": len(config.get("risk_rules", [])),
        "protected_path_patterns": len(config.get("protected_paths", [])),
        "production_path_patterns": len(config.get("production_paths", [])),
        "verification_tools": len(config.get("allowed_verification_tools", [])),
        "json_schemas": len(list((SRC / "codex_armada" / "resources" / "schemas").glob("*.json"))),
        "prompt_templates": len(list((SRC / "codex_armada" / "resources" / "prompts").glob("*.md"))),
        "runtime_dependencies": len(project["project"].get("dependencies", [])),
        "python_versions": ["3.11", "3.12", "3.13"],
        "host_families": ["Linux", "macOS", "Windows"],
        "luna_forge_version": config["luna_forge"]["required_version"],
        "luna_forge_commit": config["luna_forge"]["expected_commit"],
        "luna_equal_token_credit_reduction_vs_sol_percent": round((1.0 - luna_input / sol_input) * 100, 2),
        "terra_equal_token_credit_reduction_vs_sol_percent": round((1.0 - terra_input / sol_input) * 100, 2),
    }


def render_block(metrics: dict[str, object]) -> str:
    commit = str(metrics["luna_forge_commit"])
    return "\n".join(
        [
            START,
            "| Measured or derived result | Value | Evidence |",
            "|---|---:|---|",
            f"| Python source modules | **{metrics['python_source_modules']}** | Generated from `src/codex_armada` |",
            f"| Physical Python source lines | **{int(metrics['python_source_lines_physical']):,}** | Generated by `scripts/generate_metrics.py` |",
            f"| Automated test cases | **{metrics['automated_test_cases']}** | AST count from `tests/test_*.py` |",
            f"| CLI commands | **{metrics['cli_commands']}** | `codex-armada --help` |",
            f"| Routing profiles | **{metrics['routing_profiles']}** | `economy`, `balanced`, `quality`, `critical` |",
            f"| Runtime dependencies | **{metrics['runtime_dependencies']}** | `pyproject.toml` |",
            "| Supported Python versions | **3.11–3.13** | Package metadata and CI matrix |",
            "| Supported host families | **Linux, macOS, Windows** | CI matrix and platform-neutral runtime |",
            f"| Luna vs Sol equal-token Codex credit reduction | **{metrics['luna_equal_token_credit_reduction_vs_sol_percent']:.0f}%** | Derived from the configured official token rates |",
            f"| Terra vs Sol equal-token Codex credit reduction | **{metrics['terra_equal_token_credit_reduction_vs_sol_percent']:.0f}%** | Derived from the configured official token rates |",
            f"| Pinned Luna Forge release | **{metrics['luna_forge_version']}** | Commit `{commit[:12]}…` |",
            END,
        ]
    )


def expected_readme(metrics: dict[str, object]) -> str:
    text = README_PATH.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise SystemExit("README metrics markers are missing")
    before, remainder = text.split(START, 1)
    _, after = remainder.split(END, 1)
    return before + render_block(metrics) + after


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate reproducible Codex Armada repository metrics.")
    parser.add_argument("--check", action="store_true", help="Fail when generated metrics are stale")
    args = parser.parse_args()

    metrics = calculate()
    serialized = json.dumps(metrics, indent=2, sort_keys=True) + "\n"
    readme = expected_readme(metrics)
    if args.check:
        failures: list[str] = []
        if not METRICS_PATH.is_file() or METRICS_PATH.read_text(encoding="utf-8") != serialized:
            failures.append("docs/metrics.json is stale")
        if README_PATH.read_text(encoding="utf-8") != readme:
            failures.append("README.md metrics block is stale")
        if failures:
            raise SystemExit("; ".join(failures))
        print("Metrics are current.")
        return 0

    METRICS_PATH.write_text(serialized, encoding="utf-8")
    README_PATH.write_text(readme, encoding="utf-8")
    print(METRICS_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
