#!/usr/bin/env python3
"""Run the release-quality verification matrix for Codex Armada."""

from __future__ import annotations

import argparse
import ast
import filecmp
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import time
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"


class VerificationError(RuntimeError):
    """Raised when a release verification gate fails."""


def run(
    command: list[str],
    *,
    cwd: Path = ROOT,
    env: dict[str, str] | None = None,
    capture: bool = True,
) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(command), flush=True)
    completed = subprocess.run(
        command,
        cwd=cwd,
        env=env,
        text=True,
        capture_output=capture,
        check=False,
    )
    if not capture:
        return completed
    if completed.stdout:
        print(completed.stdout, end="" if completed.stdout.endswith("\n") else "\n")
    if completed.stderr:
        print(completed.stderr, file=sys.stderr, end="" if completed.stderr.endswith("\n") else "\n")
    return completed


def require_success(completed: subprocess.CompletedProcess[str], label: str) -> None:
    if completed.returncode != 0:
        raise VerificationError(f"{label} failed with exit code {completed.returncode}")


def count_tests() -> int:
    count = 0
    for path in sorted((ROOT / "tests").glob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        count += sum(
            1
            for node in ast.walk(tree)
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test_")
        )
    return count


def inspect_wheel(wheel: Path) -> None:
    with zipfile.ZipFile(wheel) as archive:
        names = set(archive.namelist())
    required = {
        "codex_armada/resources/default_config.toml",
        "codex_armada/resources/project_config.toml",
        "codex_armada/resources/schemas/plan.schema.json",
        "codex_armada/resources/schemas/worker.schema.json",
        "codex_armada/resources/schemas/review.schema.json",
        "codex_armada/resources/prompts/planner.md",
        "codex_armada/resources/prompts/luna-forge-worker.md",
    }
    missing = sorted(required - names)
    if missing:
        raise VerificationError(f"Wheel is missing required resources: {missing}")
    forbidden = sorted(name for name in names if "__pycache__" in name or name.endswith((".pyc", ".pyo")))
    if forbidden:
        raise VerificationError(f"Wheel contains generated bytecode: {forbidden[:5]}")


def verify_installed_cli(install_dir: Path, env: dict[str, str]) -> None:
    installed_env = env.copy()
    installed_env["PYTHONPATH"] = str(install_dir)
    version = run([sys.executable, "-m", "codex_armada", "version"], env=installed_env)
    require_success(version, "installed wheel version smoke")
    help_result = run([sys.executable, "-m", "codex_armada", "--help"], env=installed_env)
    require_success(help_result, "installed wheel help smoke")
    if "Codex Armada" not in help_result.stdout:
        raise VerificationError("Installed CLI help does not contain the project identity")


def verify_source_archive(archive: Path, env: dict[str, str]) -> None:
    with tempfile.TemporaryDirectory(prefix="codex-armada-source-smoke-") as temporary:
        root = Path(temporary)
        with zipfile.ZipFile(archive) as source:
            source.extractall(root)
        children = [path for path in root.iterdir() if path.is_dir()]
        if len(children) != 1:
            raise VerificationError(f"Expected one source archive root, found {children}")
        extracted = children[0]
        validate = run([sys.executable, "scripts/validate_repository.py"], cwd=extracted, env=env)
        require_success(validate, "extracted source repository validation")
        version = run(
            [sys.executable, "-m", "codex_armada", "version"],
            cwd=extracted,
            env={**env, "PYTHONPATH": str(extracted / "src")},
        )
        require_success(version, "extracted source CLI smoke")


def verify_git_ready_archive(archive: Path) -> None:
    with tempfile.TemporaryDirectory(prefix="codex-armada-git-ready-smoke-") as temporary:
        root = Path(temporary)
        with zipfile.ZipFile(archive) as source:
            source.extractall(root)
        children = [path for path in root.iterdir() if path.is_dir()]
        if len(children) != 1:
            raise VerificationError(f"Expected one Git-ready archive root, found {children}")
        extracted = children[0]
        inside = run(["git", "rev-parse", "--is-inside-work-tree"], cwd=extracted)
        require_success(inside, "Git-ready repository detection")
        if inside.stdout.strip() != "true":
            raise VerificationError("Git-ready archive did not extract as a Git repository")
        status = run(["git", "status", "--porcelain=v1"], cwd=extracted)
        require_success(status, "Git-ready status")
        if status.stdout.strip():
            raise VerificationError("Git-ready archive extracted with a dirty working tree")
        history = run(["git", "rev-list", "--count", "HEAD"], cwd=extracted)
        require_success(history, "Git-ready history")
        if int(history.stdout.strip()) < 2:
            raise VerificationError("Git-ready archive does not contain the logical commit history")


def write_results(path: Path, results: dict[str, object]) -> None:
    lines = [
        "Codex Armada release verification",
        "=" * 34,
        f"Status: {results['status']}",
        f"Version: {results['version']}",
        f"Source commit: {results['source_commit']}",
        f"Python: {results['python']}",
        f"Platform: {results['platform']}",
        f"Automated tests: {results['test_count']} passed, 0 failed",
        f"Repository validation: {results['repository_validation']}",
        f"Wheel build/install smoke: {results['wheel_smoke']}",
        f"Source archive smoke: {results['source_archive_smoke']}",
        f"Git-ready archive smoke: {results['git_ready_archive_smoke']}",
        f"Reproducible release artifacts: {results['reproducible_artifacts']}",
        f"Live upstream verification: {results['live_upstream']}",
        f"Duration seconds: {results['duration_seconds']}",
        "",
        "Scope note:",
        "The automated suite validates deterministic orchestration, source pinning, installation,",
        "Git isolation, schema validation, routing, evidence gates, packaging, and archive integrity.",
        "A user's real Codex entitlements, model availability, sandbox policy, and network environment",
        "remain environment-specific and are checked by `codex-armada doctor` and `canary`.",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--live-upstream", action="store_true", help="Fetch and verify the pinned Luna Forge source")
    parser.add_argument("--results", type=Path, help="Write a human-readable verification report")
    parser.add_argument("--artifact-dir", type=Path, help="Keep built wheel and archive smoke artifacts here")
    args = parser.parse_args()

    started = time.monotonic()
    test_count = count_tests()
    env = os.environ.copy()
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env["PYTHONPATH"] = str(SRC)

    validation = run([sys.executable, "scripts/validate_repository.py"], env=env)
    require_success(validation, "repository validation")

    tests = run([sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"], env=env)
    require_success(tests, "automated test suite")
    observed = sum(1 for line in tests.stderr.splitlines() if line.rstrip().endswith("... ok"))
    if observed and observed != test_count:
        raise VerificationError(f"AST counted {test_count} tests but unittest reported {observed}")

    live_upstream = "not requested"
    if args.live_upstream:
        upstream = run([sys.executable, "scripts/verify_upstream.py"], env=env)
        require_success(upstream, "live Luna Forge upstream verification")
        live_upstream = "passed"

    owned_temporary = tempfile.TemporaryDirectory(prefix="codex-armada-release-verify-")
    try:
        artifact_dir = args.artifact_dir.resolve() if args.artifact_dir else Path(owned_temporary.name)
        artifact_dir.mkdir(parents=True, exist_ok=True)
        wheel_dir = artifact_dir / "wheel"
        install_dir = artifact_dir / "installed"
        release_dir = artifact_dir / "release"
        wheel_dir.mkdir(parents=True, exist_ok=True)

        wheel_build = run(
            [
                sys.executable,
                "-m",
                "pip",
                "wheel",
                ".",
                "--no-deps",
                "--no-build-isolation",
                "--wheel-dir",
                str(wheel_dir),
            ],
            env=env,
        )
        require_success(wheel_build, "wheel build")
        wheels = list(wheel_dir.glob("codex_armada-*.whl"))
        if len(wheels) != 1:
            raise VerificationError(f"Expected exactly one wheel, found: {wheels}")
        wheel = wheels[0]
        inspect_wheel(wheel)

        install = run(
            [sys.executable, "-m", "pip", "install", "--no-deps", "--target", str(install_dir), str(wheel)],
            env=env,
        )
        require_success(install, "wheel installation")
        verify_installed_cli(install_dir, env)

        release_build = run(
            [
                sys.executable,
                "scripts/build_release.py",
                "--output-dir",
                str(release_dir),
                "--wheel",
                str(wheel),
            ],
            env=env,
        )
        require_success(release_build, "release artifact build")
        source_archives = list(release_dir.glob("*-source.zip"))
        git_archives = list(release_dir.glob("*-git-ready.zip"))
        if len(source_archives) != 1 or len(git_archives) != 1:
            raise VerificationError("Release build did not produce one source and one Git-ready archive")
        verify_source_archive(source_archives[0], env)
        verify_git_ready_archive(git_archives[0])

        rebuild_dir = artifact_dir / "release-rebuild"
        rebuild = run(
            [
                sys.executable,
                "scripts/build_release.py",
                "--output-dir",
                str(rebuild_dir),
                "--wheel",
                str(wheel),
            ],
            env=env,
        )
        require_success(rebuild, "release reproducibility rebuild")
        first_files = {path.name: path for path in release_dir.iterdir() if path.is_file()}
        second_files = {path.name: path for path in rebuild_dir.iterdir() if path.is_file()}
        if first_files.keys() != second_files.keys():
            raise VerificationError("Repeated release builds produced different artifact inventories")
        nonreproducible = [
            name
            for name in sorted(first_files)
            if not filecmp.cmp(first_files[name], second_files[name], shallow=False)
        ]
        if nonreproducible:
            raise VerificationError(f"Repeated release builds differed: {nonreproducible}")

        version_result = run([sys.executable, "-m", "codex_armada", "version"], env=env)
        require_success(version_result, "source version")
        head = run(["git", "rev-parse", "HEAD"])
        require_success(head, "source commit lookup")
        results: dict[str, object] = {
            "status": "PASS",
            "version": version_result.stdout.strip(),
            "source_commit": head.stdout.strip(),
            "python": platform.python_version(),
            "platform": platform.platform(),
            "test_count": test_count,
            "repository_validation": "passed",
            "wheel_smoke": "passed",
            "source_archive_smoke": "passed",
            "git_ready_archive_smoke": "passed",
            "reproducible_artifacts": "passed",
            "live_upstream": live_upstream,
            "duration_seconds": round(time.monotonic() - started, 3),
        }
        if args.results:
            write_results(args.results.resolve(), results)
        print(json.dumps(results, indent=2))
    finally:
        owned_temporary.cleanup()
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except VerificationError as exc:
        print(f"VERIFY FAILED: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
